/*
 * Generated by Bluespec Compiler, version 2012.01.A (build 26572, 2012-01-17)
 * 
 * On Sat Jun 28 06:09:42 IST 2014
 * 
 */

/* Generation options: keep-fires */
#ifndef __schedule_h__
#define __schedule_h__

#include "bluesim_types.h"
#include "bs_module.h"
#include "bluesim_primitives.h"
#include "bs_vcd.h"

namespace bluesim
{
  void schedule_posedge_CLK();
}

#endif /* ifndef __schedule_h__ */
